### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by jackgreenwood30** [SH-Stark/trading-dashboard#3]
Having this issue when trying > yarn start

\trading-dashboard\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:29
                } catch {}
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

**Comment by dogepng** [comment]
Any help installing this would be great, please email me jackgreeny30@icloud.com if you can help me get this working

**Comment by dogepng** [comment]
Seems to be an issue with the terser webpack node module, I have tried npm dedupe but still not working...
